### ISSUE TITLE
Mappy app no longer displays

### ISSUE THREAD

**Issue by xurion** [KenshiDRK/mappy--Kenshi-Version#10]
Been using Mappy for a while and everything was great until recently when it started to not display the app.

Now when I start it, I can see it in the alt-tab UI, but the preview of the window shows the empty dark yellow screen as if there's no map. When I alt tab to it, it doesn't appear on the screen. If it could see the map in the preview I'd assume it was simply Mappy being off screen somewhere (I have changed resolution recently). Are the settings saved somewhere so I can remove/reset them?

<img width="678" alt="mappy" src="https://user-images.githubusercontent.com/606627/54472566-06833380-47c2-11e9-92f5-e4ff2c49742f.png">

Thanks

**Comment by KenshiDRK** [comment]
The settings are saved in the registry in HKEY_CURRENT_USER\Software\MappyXI

You either erase it all or if you wanna conserve your settings, go to the profile you want to modify and change the values in Left (x axis, 0 is most left of the screen) and Top (y Axis, 0 is top of the screen)

**Comment by xurion** [comment]
Thanks - I was able to get it to work by simply deleting all settings. However, it reverted again once I loaded it up the next day.

I did a bit of digging and I narrowed it down to the Left property (HKEY_CURRENT_USER\Software\MappyXI\profiles\Xurion\Left). It was set to 3,949 (or f6d). When I set this property to zero and load the app, it works fine.

I have a two-monitor setup and the primary (left side) monitor is 4k. My guess is this is due to the recommended scaling that Windows applies to 4k monitors (150% UI scale) because I can put mappy anywhere on the 4k monitor and it exits/loads back up fine. When I position it on the second monitor, it doesn't seem to be able to calculate the position properly.

**Comment by KenshiDRK** [comment]
Problem then is windows is scaling the resolution of mappy, thats why it was set to 3949, don't use scaling for mappy.

**Comment by xurion** [comment]
Agreed, however the problem is you can't specify which apps you want exempt, and Windows is almost unusable in full 4k without UI scaling. This is  also the default behaviour on Windows, but it only manifests on a setup with two monitors.

Thanks for your help!

**Comment by KenshiDRK** [comment]
You can specify if you want an application to don't use the scaling, there is an option if you right click on the exe, go to properties and then compatibility tab. There should be an option to disble it.
