### ISSUE TITLE
Hunts - ID not working

### ISSUE THREAD

**Issue by jcv-** [KenshiDRK/mappy--Kenshi-Version#11]
I'm not sure if something changed or if it just this particular zone/mob, but using the hex ID of the mob is not working in hunts. If I provide a name of the mob, then the hunt line works properly.

Zone: Misareaux Coast
MobID: 0DF

**Comment by KenshiDRK** [comment]
Mappy was never designed to accept id for hunt.

**Comment by jcv-** [comment]
Oh, maybe I was just getting lucky before. I had been using the PHID while farming NMs for empys.

**Comment by KenshiDRK** [comment]
nvm it does, I'll check it, could you specify where that mob is?

**Comment by jcv-** [comment]
Zone = Misareaux Coast
Mob name = Diatryma
HexID = 0DF

Let me know if there is anything else

**Comment by KenshiDRK** [comment]
its due to the 0, avoid the 0 and it will work (DF), if the id has 00 then avoid both, like 001 should be just 1, another way to make sure the id is correct is to make it show the id in preferences, spawn information.

**Comment by jcv-** [comment]
Working, thanks!
