### ISSUE TITLE
Not finding instance; Eden new boot-loader.

### ISSUE THREAD

**Issue by tipwell** [KenshiDRK/mappy--Kenshi-Version#12]
Stopped working with Eden's new boot-loader (Ashita) which will be mandatory soon. It's will not find ffxi anymore. (Version 1.50)

**Comment by KenshiDRK** [comment]
you can't rename the new loader?

**Comment by tipwell** [comment]
I tried renaming it and the game just won't start. I think it's a counter measure against 3rd party app they implemented..

**Comment by KenshiDRK** [comment]
Can you check if this file works?
[mappy.zip](https://github.com/KenshiDRK/mappy--Kenshi-Version/files/3474833/mappy.zip)

**Comment by tipwell** [comment]
It seems to work yes. Thanks :)
