### ISSUE TITLE
How do I install Mappy?  Is it a plugin, addon, or a standalone program?

### ISSUE THREAD

**Issue by IBHalliwell** [KenshiDRK/mappy--Kenshi-Version#15]
Hello,

Sorry for being so dense.  I found the download (zip), but am unsure how to install it and the readme.md file gives no hints.  Is it an add-on to Windower 4 and 5, plugin to Windower 4 and 5, or like ApRadar a standalone program.

Thank you.

**Comment by KenshiDRK** [comment]
is a standalone program, to download it go to the releases tab https://github.com/KenshiDRK/mappy--Kenshi-Version/releases/tag/v1.5.1download the zip, extract it and execute the exe file

**Comment by IBHalliwell** [comment]
Hi,

The link:
https://github.com/KenshiDRK/mappy--Kenshi-Version/releases/tag/v1.5.1download

took me to a 404 page.

I did a download of what I think is the proper one, but never found an EXE
file.

Thank you.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by IBHalliwell** [comment]
OK, I was able to get the link working.

When I used the link directly from the email set by the system (of your message), I got the 404 error.  When I came to this thread and used the same link it worked.  Go figure.

**Comment by IBHalliwell** [comment]
Thank you.  I got Mappy running.  BTW, How does one make an EXE from the source?  I haven't looked at the source, but am assuming its compiled (e.g. C, C++, etc).  Thank you again.

**Comment by KenshiDRK** [comment]
you make the exe from the source you need a compiler, mappy is coded in c#

**Comment by IBHalliwell** [comment]
Thank you.

Are you accepting suggestions and if yes, how does it work?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
