### ISSUE TITLE
Mappy resizing

### ISSUE THREAD

**Issue by Heretic6667** [KenshiDRK/mappy--Kenshi-Version#16]
Howdy - I've noticed Mappy likes to sometimes resize itself when I zone.  I'm typically able to correct this with a ctrl+alt+S to resize/snap it back to my prefered viewing size, but just wanted to get this on your radar if you were unaware.  I prefer to maintain the 'snap to range' view between zones if at all possible.  If there's a toggle for this somewhere that I missed please let me know!

Appreciate the work on this program!

**Comment by KenshiDRK** [comment]
Sorry for the delayed response, that issue is caused for the maps in the same zone having different sizes, so it's not caused by mappy it self, the issue its on the mappy.ini map sizes and it requires lot of work to solve it.
