### ISSUE TITLE
Change Process It's Looking For

### ISSUE THREAD

**Issue by MatthewJHBerry** [KenshiDRK/mappy--Kenshi-Version#20]
Hello. I spoke with you on the other thread ApRadar.
ProcHelper works for some stuff. But I'd still like to be able to use Mappy, lol.

Is it possible to change what process it's looking for? Trying to use ProcHelper with Mappy produces that error.

**Comment by MatthewJHBerry** [comment]
![image](https://user-images.githubusercontent.com/39843890/147395381-03bd4b72-a686-43be-a8cf-1954e1bd5c70.png)

**Comment by KenshiDRK** [comment]
How is the loader called?

**Comment by MatthewJHBerry** [comment]
wingsloader.exe

**Comment by KenshiDRK** [comment]
can you try this one?
[mappy.zip](https://github.com/KenshiDRK/mappy--Kenshi-Version/files/7776490/mappy.zip)

**Comment by MatthewJHBerry** [comment]
That did the trick, lol
