### ISSUE TITLE
Mappy Not working in new zone

### ISSUE THREAD

**Issue by KujahFoxfire** [KenshiDRK/mappy--Kenshi-Version#21]
New endgame event Sortie has been released which starts in Kamihr Drifts but takes place in both Outer Ra'kaznar [U1] and Outer Ra'kaznar [U2].  Mappy currently does not work in [U2].

**Comment by KenshiDRK** [comment]
I have been working those days on it, I have added a new signature to detect instance id, Im testing it, but now it should detect if you are on sortie or doing an skirmish. I'll release it after testing.

**Comment by KenshiDRK** [comment]
New release should work for them.
