### ISSUE TITLE
"Unable to initialise" error on v1.5.3

### ISSUE THREAD

**Issue by xurion** [KenshiDRK/mappy--Kenshi-Version#22]
Updated today to v1.5.3 and was not able to start it due to the following error:

![image](https://user-images.githubusercontent.com/606627/202919973-debc80ae-b924-4824-87c1-99d9f02e93b2.png)

**Comment by KenshiDRK** [comment]
I guess the signature is only valid for me >.<, can you contact me on discord?

**Comment by Jrossi3334** [comment]
Same issue here. All other signatures match mappy 1.5.2 but it seems it cannot find the instance id which doesn't exist in 1.5.2.

**Comment by KenshiDRK** [comment]
does it happens if you open mappy while already logged?

**Comment by KenshiDRK** [comment]
Could you guys try this one? 
[mappy.zip](https://github.com/KenshiDRK/mappy--Kenshi-Version/files/10063059/mappy.zip)

**Comment by xurion** [comment]
Hey sorry for the delay! I tried that just now and same issue. This is when I'm already logged in.

**Comment by Jrossi3334** [comment]
Yes same issue tried when already logged in and then opened. It does show the instance name in the taskbar though. Then get that error and no map.

**Comment by KenshiDRK** [comment]
can you contact me on discord?

**Comment by KenshiDRK** [comment]
Let me know if this one works.
[mappy.zip](https://github.com/KenshiDRK/mappy--Kenshi-Version/files/10072041/mappy.zip)

**Comment by Jrossi3334** [comment]
You got it!! Good work KenshiDRK!! Thank you!!

**Comment by xurion** [comment]
> can you contact me on discord?

Hey sorry work has been keeping me busy. I'll check the latest zip and if no joy, I'll ping you later today.

**Comment by xurion** [comment]
Looks to be working fine! Thanks for the rapid turn around!

**Comment by Jrossi3334** [comment]
Yes everything seems to be back to working normal. Did not check a sortie area yet though.

**Comment by Jrossi3334** [comment]
Only thing i see that doesnt work is when entering MH from any of the starter cities it does not change the map to the MH map. Jueno and others work fine it seems. MG works fine also.

**Comment by KenshiDRK** [comment]
Fixed the mog house issue, you gotta redownload it with the maps too.

**Comment by Jrossi3334** [comment]
I redownloaded the file Kenshi but it doesnt seem the MH is fixed in the release.

**Comment by Jrossi3334** [comment]
I tried downloading the release version for the MH fix but it doesn’t seem to work. It has the same problem as before with not changing the map.

**Comment by KenshiDRK** [comment]
it does works for me, make sure to get the maps too cause had to change some for it.   https://github.com/KenshiDRK/mappy--Kenshi-Version/commit/c390016cf0c155613de4f1a8047432c7be53ad42
