### ISSUE TITLE
Map does not display

### ISSUE THREAD

**Issue by jbo96** [KenshiDRK/mappy--Kenshi-Version#23]
Hello, 
I am using your latest version but when I run the program it shows in the task bar but the map itself will not display?

**Comment by KenshiDRK** [comment]
What is exactly not displaying? the map or the square itself?

**Comment by jbo96** [comment]
Neither the map or the square where  the map should be.

**Comment by KenshiDRK** [comment]
Are you on retail or private server? Is it finding the proccess?

**Comment by jbo96** [comment]
Retail. I am assuming that you mean that it has my character name in the drop down selection? If so then yes.

**Comment by KenshiDRK** [comment]
Then probably the map is out of the screen somehow, but to know that you need to check the windows registry

**Comment by jbo96** [comment]
How would I do that?

**Comment by KenshiDRK** [comment]
You need to open the registry and find the mappyxi key, the mappy settings are stored there

**Comment by KenshiDRK** [comment]
Yes but the position is stored per character there should be a folder for each character

**Comment by jbo96** [comment]
![image](https://user-images.githubusercontent.com/20497142/209666432-ddfd44e1-4b16-413c-ac55-129c4ca1027f.png)

![image](https://user-images.githubusercontent.com/20497142/209666498-86794a7c-0b04-4dae-b1ec-96101f84de2d.png)

**Comment by KenshiDRK** [comment]
The problem is on the left key the value is to big,  set it to something lower than your x monitor resolution

**Comment by jbo96** [comment]
Awesome! I set it to 2000 and it works perfectly now. Thank you for your time and effort!

**Comment by xurion** [comment]
Maybe you have the same issue as me. I have 2x monitors and usually drag Mappy over to the second monitor. Because Windows applies a default UI scaling of 150% for large resolutions (like 4k) the stored position in registry is way off. I have to go into my registry before each use to set the left property to 0 and then redrag it back to the desired position.
