### ISSUE TITLE
Maps not loading/no functionality - horizon

### ISSUE THREAD

**Issue by demesm** [KenshiDRK/mappy--Kenshi-Version#25]
I added the 'horizon-loader' string to the list you check for the various servers, and built it. The map doesn't populate/no map images are loaded. P

Not sure how I can help out with this but here are the current signatures
![image](https://user-images.githubusercontent.com/23346713/210165500-1532b64f-b961-4216-a1f1-020125042927.png)

Example of what I get
![image](https://user-images.githubusercontent.com/23346713/210165556-e5dc86e3-e446-4713-91f4-892bd669ca56.png)
![image](https://user-images.githubusercontent.com/23346713/210165564-9174c9fa-74d9-431e-b40e-ee60bae91375.png)

**Comment by crippledgimp** [comment]
So I went and added the Horizon ProcessName along with the others today.

When trying to build the script, I'm constantly getting an error on line 720. "GameSpawn does not contain a definition for 'InstanceID' "

I bypassed line 720 and it builds, but I also get no overlay. By alt-tabbing, i can see the overlay window, but it won't show up.

Mappy attaches and finds my character, but I have the same problem of no map overlay though bypassing line 720.

**Comment by crippledgimp** [comment]
> So I went and added the Horizon ProcessName along with the others today.
> 
> When trying to build the script, I'm constantly getting an error on line 720 in FFXIGameInstance.cs. "GameSpawn does not contain a definition for 'InstanceID' "
> 
> I bypassed line 720 and it builds, but I also get no overlay. By alt-tabbing, i can see the overlay window, but it won't show up.
> 
> Mappy attaches and finds my character, but I have the same problem of no map overlay though bypassing line 720.

Responding to my own comment here.

My solution ended up being this previous thread

https://github.com/KenshiDRK/mappy--Kenshi-Version/issues/23

Changed my "Left" to decimal 0 and mappy showed up. Even still skipping over \\ line 720 in FFXIInstance.cs  it appears to be running fine.
