### ISSUE TITLE
Linux Wine support

### ISSUE THREAD

**Issue by RoseCiel** [KenshiDRK/mappy--Kenshi-Version#29]
Hello,

I am trying to run Mappy under Wine. I launch Mappy under the same prefix of my FFXI install. Mappy finds the right process, but can't find the memory signatures address. Any idea how to solve this? How can I find these signatures?

(using Wine GE Proton 8-5)

Thanks.

![Screenshot_2023-05-12_16-30-46](https://github.com/KenshiDRK/mappy--Kenshi-Version/assets/133379368/4ce9cc54-0cf2-48c8-abfb-8dcf3426ea4f)

![Screenshot_2023-05-12_16-31-34](https://github.com/KenshiDRK/mappy--Kenshi-Version/assets/133379368/8cdd1f0e-6630-4052-bcee-ae3d2a6d8e44)
![Screenshot_2023-05-12_16-36-25](https://github.com/KenshiDRK/mappy--Kenshi-Version/assets/133379368/d77e2607-39f1-44d7-8bf7-3d253442bd2b)

**Comment by KenshiDRK** [comment]
no idea what linux does to make the signatures to not work. The signatures are memory addresses to find the pointers for ffxi data, so you need a memory viewer like cheat engine to find them.

**Comment by RoseCiel** [comment]
Using scanmem, of course I find the same signatures.

I tried ApRadar. The map works, displaying NPC/Mobs too, my position is well represented, no problem of coordinates, not tested the rest. The interface is just sluggish.

Do ApRadar and Mappy work differently? I would prefer to use Mappy.

**Comment by KenshiDRK** [comment]
then I guess is a linux issue? Apradar is Visual Basic and Mappy is C#

**Comment by RoseCiel** [comment]
Of course, it is not Mappy's issue to make it work on a system on which it is not intended. I was just trying to understand to find a solution. 

Thanks for your answer.
