### ISSUE TITLE
Mappy 1.5.0

### ISSUE THREAD

**Issue by jbo96** [KenshiDRK/mappy--Kenshi-Version#3]
When the map window is resized, I am unable to expand it back to original size. the resize arrow is not present after the original size adjustment.

**Comment by KenshiDRK** [comment]
This is not happening to me, make sure you have the resizable option checked.

**Comment by jbo96** [comment]
I have it checked but still have the issue, i have tried to delete the folder completely and redownload but it seems to keep the same settings.

**Comment by jbo96** [comment]
I am on win10 if that helps any

**Comment by jbo96** [comment]
OK, I am sorry for the trouble. but i got it to work, if the map window is over the FFXI client it works fine but if you have it over on your other monitor the left/right resize doesn't work but the top/bottom does. again i do apologize for the trouble
