### ISSUE TITLE
How to install mappy

### ISSUE THREAD

**Issue by Fuvi211118** [KenshiDRK/mappy--Kenshi-Version#31]
Please i need help install the mappy i dont know how to install help please

**Comment by KenshiDRK** [comment]
mappy doesn't install, you just have to run the exe file, you probably got the source code, get the release here https://github.com/KenshiDRK/mappy--Kenshi-Version/releases/tag/v1.5.6

**Comment by Fuvi211118** [comment]
> mappy doesn't install, you just have to run the exe file, you probably got the source code, get the release here https://github.com/KenshiDRK/mappy--Kenshi-Version/releases/tag/v1.5.6

you got discord I need help with something please

**Comment by KenshiDRK** [comment]
yea, you can contact me there, kenshidrk is my username

**Comment by Fuvi211118** [comment]
> yea, you can contact me there, kenshidrk is my username

Yes I have sent an invite please accept it
