### ISSUE TITLE
Mappy.exe version 1.50

### ISSUE THREAD

**Issue by xxxKaiserxxx** [KenshiDRK/mappy--Kenshi-Version#4]
Hello,

This is Xeye from the windower official forums.

I'm using right now version 1.49 and I want to download the new version but I couldn't find the .exe, Is it still in development or am i missing something?

Thank you so much Kenshi for your amazing work as always! I keep checking your page here every few days to see if you have something new. /stalker xD

**Comment by KenshiDRK** [comment]
Im waiting mainly till all the other new dynamis zones are released. I can add a prerelease if ppl want it.

**Comment by xxxKaiserxxx** [comment]
I see.

No need for a pre-release. I can wait till you add all the new zones in the near future. (but if you want you can add a note or a message about it in the read me file for the people who is looking for the new release like me ^.^)

Thank you, Kenshi. (I'm gonna close it since I got my answer <3)
