### ISSUE TITLE
The app no longer starts up

### ISSUE THREAD

**Issue by Rikimarueye** [KenshiDRK/mappy--Kenshi-Version#6]
When I start up the application after the June update, it crashes with a error dialogue box.
 It says Microsoft .NET Framework encountered a unhandled exception in the application.

**Comment by KenshiDRK** [comment]
It does work for me, are you playing on a private server?

**Comment by Rikimarueye** [comment]
No, I play on the official servers.

**Comment by Rikimarueye** [comment]
Really sowwi to bother you ^^; After updating to newest version of win10, the application loads again.
