### ISSUE TITLE
Dynamis Divergence

### ISSUE THREAD

**Issue by W1ndowpane** [KenshiDRK/mappy--Kenshi-Version#8]
Hi,

I downloaded the most recent folders and replaced my old ones but the Dynamis divergence make are still blank. Am I doing something wrong or is there a quick fix to get them to appear? 

Thanks.

**Comment by KenshiDRK** [comment]
you need to replace the most recent exe, and the init file.

**Comment by W1ndowpane** [comment]
I swear I was only able to find the exe when I initially downloaded it. What is the best way to get it?
